version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:7.4.30
      - image: cimg/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          DB_CONNECTION: mysql_test
          DB_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: market_test
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/src

    steps:
      - checkout

      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 60`; do
              nc -z localhost 3306 && echo "MySQL is up" && break
              echo "Waiting for MySQL..."
              sleep 2
            done

      - run:
          name: Move to src directory
          command: cd src

      - run:
          name: base64 decode env file
          command: echo $ENV_TEST_FILE | base64 -di > src/.env.testing

      - run:
          name: Update Composer to Version 2
          command: sudo composer self-update --2

      - run:
          name: Check for composer.json
          command: |
            if [ ! -f src/composer.json ]; then
              echo "composer.json file not found in $(pwd)/src"
              exit 1
            fi

      - restore_cache:
          key: composer-v2-{{ checksum "src/composer.lock" }}

      - run:
          name: Install Dependencies
          command: cd src && composer install -n --prefer-dist

      - save_cache:
          key: composer-v2-{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor

      - run:
          name: Run Migrations
          command: cd src && php artisan migrate --env=testing

      - run:
          name: Run Tests
          command: cd src && php artisan test --env=testing

