version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4.9
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/src/src

    steps:
      - checkout

      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 30`; do
              nc -z localhost 3306 && echo "MySQL is up" && break
              echo "Waiting for MySQL..."
              sleep 2
            done

      - run:
          name: base64 decode env file
          command: echo $ENV_TEST_FILE | base64 -di > .env.testing

      - run:
          name: Update Composer to Version 2
          command: sudo composer self-update --2

      - restore_cache:
          key: composer-v2-{{ checksum "composer.lock" }}

      - run:
          name: Install Dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          key: composer-v2-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run:
          name: Run Migrations
          command: php artisan migrate --env=testing

      - run:
          name: Run Tests
          command: php artisan test --env=testing
