version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4.9
      - image: circleci/mysql:8.0.26

    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:AKaEDIOPONtYxErF0RqDXTdyN3tsUJ9AXLXAApqX4eQ=
      - DB_CONNECTION: mysql_test
      - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/src

    steps:
      - checkout
      - run: php artisan migrate
      - run: php artisan test